### PR TITLE
Clarify `stat_max`

### LINKED ISSUE #193: Fix disparities in meaning of `stat_max` in various functions
The definition of `stat_max` in `simulate_chains()` is not entirely correct and in particular, the part that says "Results above `stat_max` are set to `stat_max`." I think this is a remnant from the original definition in `bpmodels::chain_sim()`. 

`stat_max` in `simulate_chains()` is now the upper bound of the tracked statistic above which chain simulations are halted. The default of `Inf` means that no upper bound is used. We could add further explanation and guidance to say that it is used internally to ensure that outbreaks with R0 > 1 do not continue forever, so when a user sets an offspring mean above 1 coupled with an infinite population, they need to choose a finite value. Furthermore, `stat_max` in `simulate_chains()` should probably be renamed to something like `chain_sim_cutoff` to remove confusion between it and `stat_max` in `simulate_summary()` and `likelihood()`, which is the value above which stat is set to `Inf` in the former and set to `stat_max` in the latter. Renaming it in `simulate_chains()` will resolve #163.

On the above point,  we need to consider using a single definition & operation that can be inherited between `simulate_summary()` and `likelihood()` as these varying definitions might be a pointer to design considerations that need to be improved.

@sbfnk Methodologically, what would be wrong with doing `stat_track[stat_track >= stat_max] <- stat_max`?  in `simulate_summry()` below?

https://github.com/epiverse-trace/epichains/blob/0941451525900125a3dade95b1f8c317d71a4043/R/simulate.r#L414

to align with what's done in `likelihood()`?

https://github.com/epiverse-trace/epichains/blob/0941451525900125a3dade95b1f8c317d71a4043/R/likelihood.R#L97

### PR DESCRIPTION
**Pull request by jamesmbaazam**
This PR closes #193 by renaming `stat_max` to `stat_threshold` and improves the documentation to help clarify some nuances between `stat_threshold` in `simulate_chains()` and `simulate_summary()`. It also renames the `infinite` argument (old name of `stat_max`) in `rborel()` to `censor_at` and improves its documentation. In particular,

- `stat_threshold` in `simulate_chains()` is a stopping criterion for chains. When the cumulative statistic of chains reaches or surpasses it, they end
- `stat_threshold` in `simulate_summary()` is both a stopping criterion for chains and a censoring limit. When the cumulative statistics of chains reach or surpass it, they end. Additionally, chain statistic values that are >= `stat_threshold` are set to `Inf`.
- `censor_at` in the borel functions is passed to `stat_threshold` in `simulate_summary()` as a stopping criterion and for censoring chain sizes but does not refer to chain sizes as used in `simulate_summary()`, hence the name change and dedicated documentation.

### CODE REVIEW

**Comment by jamesmbaazam** [comment]
The need to clarify this argument came up today in the tutorial. A participant asked, "Why do some chains produce more cumulative cases than what `stat_max`` is?" My answer was roughly, "Chains may still produce more cases than `stat_max` near the stopping criterion but will not continue to produce more cases after the stopping criterion is met. For example, if the stopping criterion is 10 cases, the chain may produce 12 cases near the stopping criterion." This raises the need to clarify `stat_max` further as it suggests that chains cannot produce a statistic above it.

@joshwlambert and @avallecam Do you have thoughts on how to clarify this further? I'm tagging you because we had a brief discussion about it after the tutorial session.

File: R/borel.r [hunk 1]
```diff
@@ -27,19 +27,14 @@ dborel <- function(x, mu, log = FALSE) {
 ##' Random numbers are generated by simulating from a Poisson branching process
 ##' @param n Number of random variates to generate.
 ##' @inheritParams dborel
-##' @param infinite A threshold above which the random number is set to
-##'  `Inf` as a form of truncation. This is important because `rborel()` uses
-##'  `simulate_summary()` internally with `offspring_dist = rpois`, so
-##'  when `mu >= 1`, the simulation could grow out of proportion and chain
-##'  summaries (the random numbers generated here) need to be truncated using
-##'  `infinite`.
+##' @inheritParams simulate_summary
```
Comment (sbfnk) [inline R/borel.r:30]: If doing this we'll have to change the documentation of the argument in `simulate_summary()` as it refers to a `statistic` argument which does not exist here.

Perhaps just rename it to `max` and keep the documentation as is?

File: R/simulate.r [hunk 2]
```diff
@@ -25,8 +25,11 @@
 #'   \item "length": the total number of ancestors produced by a chain before
 #'   it goes extinct.
 #' }
-#' @param stat_max A cut off for the chain statistic (size/length) being
-#' computed. Results above `stat_max` are set to `stat_max`. Defaults to `Inf`.
+#' @param stat_max A stopping criterion for individual chain simulations; a
+#' positive number coercible to integer. When any chain's cumulative statistic
+#' reaches `stat_max`, that chain ends. Defaults to `Inf`. For example, if
```
[the remark this answers is not in the document]
Comment (sbfnk) [reply R/simulate.r:30]: maybe "reaches or surpasses"? Because if the statistic reaches `stat_max` the chain ends.

**Review by sbfnk — COMMENTED** [review]
> Why do some chains produce more cumulative cases than what `stat_max` is?

Would an alternative be to ensure it doesn't, i.e. select cases in the final generation such that the stat is `stat_max`?

**Comment by joshwlambert** [comment]
> Would an alternative be to ensure it doesn't, i.e. select cases in the final generation such that the stat is `stat_max`?

My preference would be to either 1) keep the name `stat_max` and make it a hard limit for the simulation so the user cannot exceed this number, or 2) change the argument name to replace `max` with another word that doesn't imply a hard limit and then improve documentation to how this works. 

This is where I think the confusion stemmed from in the tutorial because it is a _max_ that does not behave as a _max_.

**Comment by joshwlambert** [comment]
FYI we have the same functionality dilemma in {simulist} and have chosen to have a soft limit so the "maximum" can be exceeded and the function returns a warning to let the user know the "maximum" (either default `1e4` or user-specified) has been exceeded and states the number of cases returned.

https://github.com/epiverse-trace/simulist/blob/main/R/sim_linelist.R#L70

This discussion also makes it clear that the documentation in `sim_linelist()` could also be improved.

**Comment by jamesmbaazam** [comment]
> Would an alternative be to ensure it doesn't, i.e. select cases in the final generation such that the stat is `stat_max`?

I think this might be the desirable behaviour. We could treat the last generation of offspring as potential offspring and sample the number needed to reach `stat_max` by finding the difference between the cumulative number before the last generation and `stat_max`.

**Comment by jamesmbaazam** [comment]
> > Would an alternative be to ensure it doesn't, i.e. select cases in the final generation such that the stat is `stat_max`?
> 
> My preference would be to either 1) keep the name `stat_max` and make it a hard limit for the simulation so the user cannot exceed this number, or 2) change the argument name to replace `max` with another word that doesn't imply a hard limit and then improve documentation to how this works.
> 
> This is where I think the confusion stemmed from in the tutorial because it is a _max_ that does not behave as a _max_.

Thanks, Josh.

I think option 1 is better because it can be used to simulate desirable behavior. Allowing simulations to go beyond the limit set will make the results difficult to explain.

**Comment by jamesmbaazam** [comment]
> FYI we have the same functionality dilemma in {simulist} and have chosen to have a soft limit so the "maximum" can be exceeded and the function returns a warning to let the user know the "maximum" (either default `1e4` or user-specified) has been exceeded and states the number of cases returned.
> 
> [epiverse-trace/simulist@`main`/R/sim_linelist.R#L70](https://github.com/epiverse-trace/simulist/blob/main/R/sim_linelist.R?rgh-link-date=2024-05-03T10%3A10%3A12Z#L70)
> 
> This discussion also makes it clear that the documentation in `sim_linelist()` could also be improved.

I may be misinterpreting your definition of "soft" but from the code & output, it does seem like you don't return values above the max, so I would still interpret it as a "hard" limit.

**Comment by joshwlambert** [comment]
> I think option 1 is better because it can be used to simulate desirable behavior. Allowing simulations to go beyond the limit set will make the results difficult to explain.

Sounds good to me.

> I may be misinterpreting your definition of "soft" but from the code & output, it does seem like you don't return values above the max, so I would still interpret it as a "hard" limit.

Here's a reprex to show what I mean. The `outbreak_size` argument takes a vector of two elements a hard lower limit, and a soft upper limit for the outbreak size.

``` r
set.seed(2)
library(simulist)
linelist <- sim_linelist(
  contact_distribution = function(x) dpois(x = x, lambda = 2),
  infect_period = function(x) dgamma(x = x, shape = 3, scale = 3),
  prob_infect = 0.55,
  onset_to_hosp = function(x) dgamma(x = x, shape = 2, scale = 2),
  onset_to_death = function(x) dgamma(x = x, shape = 2, scale = 2),
  outbreak_size = c(5, 20)
)
#> Warning: Number of cases exceeds maximum outbreak size. 
#> Returning data early with 29 cases and 44 total contacts (including cases).
```

<sup>Created on 2024-05-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jamesmbaazam** [comment]
> > I think option 1 is better because it can be used to simulate desirable behavior. Allowing simulations to go beyond the limit set will make the results difficult to explain.
> 
> Sounds good to me.
> 
> > I may be misinterpreting your definition of "soft" but from the code & output, it does seem like you don't return values above the max, so I would still interpret it as a "hard" limit.
> 
> Here's a reprex to show what I mean. The `outbreak_size` argument takes a vector of two elements a hard lower limit, and a soft upper limit for the outbreak size.
> 
> ```r
> set.seed(2)
> library(simulist)
> linelist <- sim_linelist(
>   contact_distribution = function(x) dpois(x = x, lambda = 2),
>   infect_period = function(x) dgamma(x = x, shape = 3, scale = 3),
>   prob_infect = 0.55,
>   onset_to_hosp = function(x) dgamma(x = x, shape = 2, scale = 2),
>   onset_to_death = function(x) dgamma(x = x, shape = 2, scale = 2),
>   outbreak_size = c(5, 20)
> )
> #> Warning: Number of cases exceeds maximum outbreak size. 
> #> Returning data early with 29 cases and 44 total contacts (including cases).
> ```
> 
> Created on 2024-05-03 with [reprex v2.1.0](https://reprex.tidyverse.org)

Ah! Thanks for this. That makes sense. I don't think we should have a hard lower limit in {epichains} as it is by definition the seeing cases, if the outbreak doesn't take off. The soft upper limit is what is already implemented as `stat_max`, so it's currently a matter of documentation which can be solved with a name change and a proper wording. 

My concern is more about whether it is desirable behaviour. For example, if a user sets `stat_max` to 500 cases and gets `800` cases, that's quite undesirable. I think the solution would be what I suggested in  https://github.com/epiverse-trace/epichains/pull/237#issuecomment-2092761867, where we sample the remainder from the excess cases and return exactly `stat_max`.

File: R/borel.r (hunk 1 above)
Comment (jamesmbaazam) [reply R/borel.r]: That's true. I've renamed it to `censor_at` in 55e8cfed89fc8b7e3b35ea77f0e8d9c257da4a78 and clarified the documentation to reflect the fact that values are replaced with `Inf` at the given censoring limit and simulations are stopped.

File: R/borel.r [hunk 3]
```diff
@@ -27,20 +27,18 @@ dborel <- function(x, mu, log = FALSE) {
...
-##'  argument is important because `rborel()` uses `simulate_summary()`
-##'  internally with `offspring_dist = rpois`, so when `mu >= 1`, the
-##'  simulation could grow out of proportion and chain summaries (the random
-##'  numbers generated here) need to be truncated using
-##'  `infinite`.
+##' @param censor_at A stopping criterion; `<numeric>`. Defaults to `Inf`. A
+##' value above which the simulation ends and the random number is set to
+##' `Inf` (as a form of censoring). `rborel()` uses [simulate_summary()]
+##' internally with a poisson offspring distribution, so if `mu >= 1`, the
+##' simulation could proceed unendingly. This parameter is used to prevent this.
```
Comment (jamesmbaazam) [inline R/borel.r:34]:
```suggestion
##' `Inf` (as a form of censoring). `rborel()` simulates chain sizes using [simulate_summary()]
##'  with a Poisson offspring distribution, so if `mu >= 1`, the
##' simulation could proceed unendingly. This parameter is used to prevent this.
```

**Comment by jamesmbaazam** [comment]
Upon further discussion with Seb, we've decided it might be better to rename `stat_max` to `stat_threshold` and improve the wording to indicate that it is not a hard limit and can be exceeded due to stochastic effects. The discussion about making it a hard limit has been logged in #243 for further brainstorming.

**Review by sbfnk — APPROVED** [review]
